name: Infra + Ansible + Trigger Azure Pipeline

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - run: terraform init
        working-directory: ./infra/terraform

      - run: terraform apply -auto-approve
        working-directory: ./infra/terraform

  ansible:
    name: Configure VMs
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo apt update
          sudo apt install -y ansible
          ansible-galaxy collection install azure.azcollection
        name: Install Ansible

      - run: |
          ansible-playbook -i ansible/inventories/azure_rm.yml ansible/playbooks/configure-vms.yml
        name: Run Ansible

  trigger_azure_devops:
    name: Trigger Azure DevOps Pipeline
    runs-on: ubuntu-latest
    needs: ansible

    steps:
      - name: Call Azure DevOps Pipeline
        run: |
          curl -X POST \
            -H "Authorization: Basic ${{ secrets.AZURE_DEVOPS_PAT_BASE64 }}" \
            -H "Content-Type: application/json" \
            https://dev.azure.com/vivekazure2354/Terraform/_apis/pipelines/23/runs?api-version=7.1-preview.1 \
            -d '{"resources": { "repositories": { "self": { "refName": "refs/heads/main" }}}}'
